### ISSUE TITLE
Supported Hugo version

### ISSUE THREAD

**Issue by Trickx** [curtiscde/hugo-theme-massively#111]
config.toml defines a maximum supported version of Hugo 0.94.2.
What about newer versions?
Are there known issues or newer version simply haven't been tested, yet?

```
[module]
  [module.hugoVersion]
    min = "0.54.0"
    max = "0.94.2"
```
   
[config.toml](https://github.com/curtiscde/hugo-theme-massively/blob/master/config.toml)

**Comment by curtiscde** [comment]
Hi @Trickx 🙂 

It is just defined as a max version of `0.94.2` as that is the latest version to have been ran against the automated tests, there's every chance newer versions will work fine.

Is there a particular version you were wishing to use the theme with? Are you having any specific issues

**Comment by curtiscde** [comment]
This theme has now been successfully tested against the current latest version of Hugo, [v0.101.0](https://github.com/gohugoio/hugo/releases/tag/v0.101.0).

Please let me know if there are any specific issues you are facing.

**Comment by Trickx** [comment]
Hi curtiscde,
thank you for the prompt reply.
I'm a newbie in Hugo and just started to build my setup.
Hugo generated a warning message regarding unsupported version, so asked myself whether this is an issue or not.
Except my greenness - I'm not aware of any issues.

**Comment by curtiscde** [comment]
Thanks @Trickx, it was a good prompt to update the max version. The e2e tests have also been updated to test against both the min and max version now.

If you have any problems, please feel to raise an issue!
