### ISSUE TITLE
FR: Allow custom CSS

### ISSUE THREAD

**Issue by stephlocke** [curtiscde/hugo-theme-massively#19]
Enable users to provide a custom css file in their `static/` dir.

**Comment by UtkarshVerma** [comment]
@stephlocke I'm working on this.

**Comment by curtiscde** [comment]
The latest version of this theme now supports custom CSS 🙂 #105 

https://github.com/curtiscde/hugo-theme-massively/releases/tag/v6.2.0

https://github.com/curtiscde/hugo-theme-massively#custom-head
