### ISSUE TITLE
Configure cover image URL

### ISSUE THREAD

**Issue by curtiscde** [curtiscde/hugo-theme-massively#43]
Currently the cover image is hard-coded to:

```
/static/images/bg.jpg
```

https://github.com/curttimson/hugo-theme-massively#cover-image

Allow this to be configured.

**Comment by Kaligule** [comment]
The point where this is hardcoded is here: [assets/scss/layout/_wrapper.scss#L22](https://github.com/curtistimson/hugo-theme-massively/blob/b486b3d83b9ff134944c6f1e9ad6a9ba0aee4806/assets/scss/layout/_wrapper.scss#L22)

I don't know how scss files can be templated/rendered to include variables from the config, though.
