### ISSUE TITLE
Possible to use a post image from a Page Resource?

### ISSUE THREAD

**Issue by omrihar** [curtiscde/hugo-theme-massively#66]
First off, thank you for the really nice theme! I'm still trying to wrap my head around Hugo (coming from the python world) and I think I'm slowly getting there... 
I recently discovered Page Bundles and really like the idea of organizing my images in the same folder as a post rather than placing them in the `static` folder. What I don't know how to do is - I'd like to set the `image` parameter in the YAML front matter to an image from the Page Bundle (i.e. from the post directory). I tried simply giving a path, which didn't work. I also tried renaming the file by using the `resources` parameter, but to no avail. 
Is this possible to do? Do I need to overwrite the way the theme is loading the image from that parameter to make this work?

Any help or pointers are welcome!
Cheers,
Omri

**Comment by curtistimson** [comment]
Hi Omri, welcome to Hugo!

As you have a generic Hugo question I recommend posting on the official Hugo forum with your query:

https://discourse.gohugo.io
