### ISSUE TITLE
Image on post not full when using mobile-view

### ISSUE THREAD

**Issue by donihalim** [curtiscde/hugo-theme-massively#82]
Hello
First, thanks for the bautifull theme.
I have an issue with mobile-view, the image on post not fully showing or get cropped as shown bellow.
Check the original post : https://linuxlewd.netlify.com/post/sudo-lecture/

Thank you.

![Screenshot_20191130-185253_cropped](https://user-images.githubusercontent.com/57899491/69900166-c3dea700-13a2-11ea-8810-9cab5b21b272.png)

**Comment by MAO202012** [comment]
adjust in https://github.com/curtistimson/hugo-theme-massively/pull/97

**Comment by RuifMaxx** [comment]
adjust in https://github.com/curtistimson/hugo-theme-massively/pull/97

**Comment by RuifMaxx** [comment]
the pr may help you, with the latest hugo version. https://github.com/curtistimson/hugo-theme-massively/pull/97

**Comment by curtiscde** [comment]
This has been resolved by #97
