### ISSUE TITLE
Question: is it possible to make the "Full Story" links go to a different URL rather than internally?

### ISSUE THREAD

**Issue by brimwats1** [curtiscde/hugo-theme-massively#90]
I want to use this theme for histsex.com, as it's just perfect, but I'd rather make it so folks can just skip the click between the front page, another page and then an omeka

**Comment by brimwats** [comment]
for others that come along: you can use a .htaccess file to do this, but I was looking for something native

**Comment by Kaligule** [comment]
Could you describe what you want in more detail, please? I don't know what you mean by "skip the click" and where you want to skip it.

**Comment by brimwats** [comment]
check out histsex.com and you'll see. I had to use the .htaccess file to do this, this way items 1-4 go to the omeka, vs the introduction which goes to a post

**Comment by brimwats** [comment]
e.g. the read more link for Research Locations goes to https://histsex.com/omeka/s/50yo/page/collections

the read more for the introduction post goes to
https://histsex.com/post/introduction/

**Comment by curtiscde** [comment]
Hi @brimwats1, this is not available with the current version. Please feel free to create a PR with configuration options if this is something you would like to see.
