### ISSUE TITLE
Is it possible to change the text at the top of the theme?

### ISSUE THREAD

**Issue by brimwats1** [curtiscde/hugo-theme-massively#91]
I'd like to use a black and white image for www.histsex.com, but the white text gets washed out when this is tried. Is it possible to add a dark box behind the text, or to change the text color?

**Comment by asolisc** [comment]
I have the same problem. Has anyone been succesful?

**Comment by WillNaylor1994** [comment]
> I'd like to use a black and white image for [www.histsex.com](http://www.histsex.com), but the white text gets washed out when this is tried. Is it possible to add a dark box behind the text, or to change the text color?

Not sure about the box, but changing the text colour would be easy.

Just search 'intro h1' in your text editor to see where the css is.

It's in main.scss line 2069, the colour is et to #ffffff which means white. you can update to any hex colour here.

**Comment by curtiscde** [comment]
[v6.2.0](https://github.com/curtiscde/hugo-theme-massively/releases/tag/v6.2.0) introduces the ability to add custom HTML `<head>` elements by creating a new file to inject them as described here:

https://github.com/curtiscde/hugo-theme-massively#custom-head

In the new file you could then add reference to a new CSS file:

```html
<link href="/css/custom.css" rel="stylesheet" />
```

Your `custom.css` could then apply overriding styles to update the header, for example:

```css
h1 {
    background: #000;
    padding: 10px;
}
```

I hope this helps!
