### ISSUE TITLE
Is it possible to add a non-blog post page?

### ISSUE THREAD

**Issue by whittles** [curtiscde/hugo-theme-massively#95]
I would like to add a page that is an about page but not have it mixed in with the blog post feed and a link to it in the main navigation. Is this possible and I am just missing it?

**Comment by curtiscde** [comment]
Hi @whittles, this is not possible with the current version of this theme, but please feel free to open a PR to add this feature :)

**Comment by curtiscde** [comment]
This feature has now been added as part of [v6.3.0](https://github.com/curtiscde/hugo-theme-massively/releases/tag/v6.3.0)

https://hugo-theme-massively.netlify.app/generic-page

https://github.com/curtiscde/hugo-theme-massively/blob/master/exampleSite/content/generic-page.en.md
