### ISSUE TITLE
Auto scaling images

### ISSUE THREAD

**Issue by jchannon** [curtiscde/hugo-theme-massively#99]
I have some markdown with a image referenced, when displayed on my blog using the theme it shows the actual size of the image which is far larger than the width of the blog design, is there something that can be done to make the image fit within the blog width when viewed at desktop or mobile?

Thanks

**Comment by curtiscde** [comment]
Hi @jchannon, thanks for raising this.

Please feel free to raise a PR to address this issue. Meanwhile I'll keep this issue open as a bug in case anyone else comes up with a solution.

**Comment by curtiscde** [comment]
@jchannon This has now been fixed as part of #97 🙂 

Please update your theme to [v6.2.1](https://github.com/curtiscde/hugo-theme-massively/releases/tag/v6.2.1), and if you are still having issues, you reopen this issue.
